[2021-05-17 00:46:47,873] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.list_files 2021-05-16T19:46:44.068363+00:00 [queued]>
[2021-05-17 00:46:47,881] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.list_files 2021-05-16T19:46:44.068363+00:00 [queued]>
[2021-05-17 00:46:47,881] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 00:46:47,881] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-05-17 00:46:47,881] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 00:46:47,912] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): list_files> on 2021-05-16T19:46:44.068363+00:00
[2021-05-17 00:46:47,917] {standard_task_runner.py:53} INFO - Started process 30323 to run task
[2021-05-17 00:46:48,009] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: bigquery_data_load.list_files 2021-05-16T19:46:44.068363+00:00 [running]> alieymsxxn
[2021-05-17 00:46:48,019] {taskinstance.py:1145} ERROR - list_objects() got an unexpected keyword argument 'conf'
Traceback (most recent call last):
  File "/home/alieymsxxn/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/alieymsxxn/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/alieymsxxn/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: list_objects() got an unexpected keyword argument 'conf'
[2021-05-17 00:46:48,021] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=bigquery_data_load, task_id=list_files, execution_date=20210516T194644, start_date=20210516T194647, end_date=20210516T194648
[2021-05-17 00:46:57,851] {logging_mixin.py:112} INFO - [2021-05-17 00:46:57,850] {local_task_job.py:103} INFO - Task exited with return code 1
