[2021-05-16 19:37:54,960] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.load_data 2021-05-16T13:00:00+00:00 [queued]>
[2021-05-16 19:37:54,972] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.load_data 2021-05-16T13:00:00+00:00 [queued]>
[2021-05-16 19:37:54,972] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 19:37:54,972] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-05-16 19:37:54,972] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 19:37:55,007] {taskinstance.py:900} INFO - Executing <Task(GoogleCloudStorageToBigQueryOperator): load_data> on 2021-05-16T13:00:00+00:00
[2021-05-16 19:37:55,010] {standard_task_runner.py:53} INFO - Started process 13007 to run task
[2021-05-16 19:37:55,099] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: bigquery_data_load.load_data 2021-05-16T13:00:00+00:00 [running]> alieymsxxn
[2021-05-16 19:38:01,190] {taskinstance.py:1145} ERROR - BigQuery job failed. Final error was: {'reason': 'notFound', 'message': 'Not found: Uris gs://ma-logistics/*'}. The job was: {'kind': 'bigquery#job', 'etag': 'Dnwe9oHRLRoxe4dfmQ+FIQ==', 'id': 'ma-airflow:asia-south1.job_BVGX-FhFzemmdCO_fxSOz5YF8E_a', 'selfLink': 'https://bigquery.googleapis.com/bigquery/v2/projects/ma-airflow/jobs/job_BVGX-FhFzemmdCO_fxSOz5YF8E_a?location=asia-south1', 'user_email': 'airflow@ma-airflow.iam.gserviceaccount.com', 'configuration': {'load': {'sourceUris': ['gs://ma-logistics/*'], 'destinationTable': {'projectId': 'ma-airflow', 'datasetId': 'analytics', 'tableId': 'history'}, 'createDisposition': 'CREATE_IF_NEEDED', 'writeDisposition': 'WRITE_APPEND', 'fieldDelimiter': ',', 'skipLeadingRows': 1, 'encoding': 'UTF-8', 'allowQuotedNewlines': False, 'sourceFormat': 'CSV', 'ignoreUnknownValues': False, 'autodetect': True}, 'jobType': 'LOAD'}, 'jobReference': {'projectId': 'ma-airflow', 'jobId': 'job_BVGX-FhFzemmdCO_fxSOz5YF8E_a', 'location': 'asia-south1'}, 'statistics': {'creationTime': '1621175878379', 'startTime': '1621175878650', 'endTime': '1621175878852'}, 'status': {'errorResult': {'reason': 'notFound', 'message': 'Not found: Uris gs://ma-logistics/*'}, 'errors': [{'reason': 'notFound', 'message': 'Not found: Uris gs://ma-logistics/*'}], 'state': 'DONE'}}
Traceback (most recent call last):
  File "/home/alieymsxxn/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/alieymsxxn/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/contrib/operators/gcs_to_bq.py", line 288, in execute
    encryption_configuration=self.encryption_configuration)
  File "/home/alieymsxxn/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 1297, in run_load
    return self.run_with_configuration(configuration)
  File "/home/alieymsxxn/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 1344, in run_with_configuration
    format(job['status']['errorResult'], job))
Exception: BigQuery job failed. Final error was: {'reason': 'notFound', 'message': 'Not found: Uris gs://ma-logistics/*'}. The job was: {'kind': 'bigquery#job', 'etag': 'Dnwe9oHRLRoxe4dfmQ+FIQ==', 'id': 'ma-airflow:asia-south1.job_BVGX-FhFzemmdCO_fxSOz5YF8E_a', 'selfLink': 'https://bigquery.googleapis.com/bigquery/v2/projects/ma-airflow/jobs/job_BVGX-FhFzemmdCO_fxSOz5YF8E_a?location=asia-south1', 'user_email': 'airflow@ma-airflow.iam.gserviceaccount.com', 'configuration': {'load': {'sourceUris': ['gs://ma-logistics/*'], 'destinationTable': {'projectId': 'ma-airflow', 'datasetId': 'analytics', 'tableId': 'history'}, 'createDisposition': 'CREATE_IF_NEEDED', 'writeDisposition': 'WRITE_APPEND', 'fieldDelimiter': ',', 'skipLeadingRows': 1, 'encoding': 'UTF-8', 'allowQuotedNewlines': False, 'sourceFormat': 'CSV', 'ignoreUnknownValues': False, 'autodetect': True}, 'jobType': 'LOAD'}, 'jobReference': {'projectId': 'ma-airflow', 'jobId': 'job_BVGX-FhFzemmdCO_fxSOz5YF8E_a', 'location': 'asia-south1'}, 'statistics': {'creationTime': '1621175878379', 'startTime': '1621175878650', 'endTime': '1621175878852'}, 'status': {'errorResult': {'reason': 'notFound', 'message': 'Not found: Uris gs://ma-logistics/*'}, 'errors': [{'reason': 'notFound', 'message': 'Not found: Uris gs://ma-logistics/*'}], 'state': 'DONE'}}
[2021-05-16 19:38:01,192] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=bigquery_data_load, task_id=load_data, execution_date=20210516T130000, start_date=20210516T143754, end_date=20210516T143801
[2021-05-16 19:38:04,933] {logging_mixin.py:112} INFO - [2021-05-16 19:38:04,932] {local_task_job.py:103} INFO - Task exited with return code 1
