[2021-05-17 00:41:34,412] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.move_files 2021-05-16T19:40:33.735177+00:00 [queued]>
[2021-05-17 00:41:34,422] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.move_files 2021-05-16T19:40:33.735177+00:00 [queued]>
[2021-05-17 00:41:34,422] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 00:41:34,422] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-05-17 00:41:34,422] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 00:41:34,457] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): move_files> on 2021-05-16T19:40:33.735177+00:00
[2021-05-17 00:41:34,463] {standard_task_runner.py:53} INFO - Started process 29157 to run task
[2021-05-17 00:41:34,541] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: bigquery_data_load.move_files 2021-05-16T19:40:33.735177+00:00 [running]> alieymsxxn
[2021-05-17 00:41:34,552] {taskinstance.py:1145} ERROR - 'ti'
Traceback (most recent call last):
  File "/home/alieymsxxn/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/alieymsxxn/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/alieymsxxn/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alieymsxxn/Documents/Projects/airflow/airflow_home/dags/bigquery_data_load.py", line 26, in move_objects
    storage_objects = kwargs['ti'].xcom_pull(task_id='list_files')
KeyError: 'ti'
[2021-05-17 00:41:34,554] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=bigquery_data_load, task_id=move_files, execution_date=20210516T194033, start_date=20210516T194134, end_date=20210516T194134
[2021-05-17 00:41:44,380] {logging_mixin.py:112} INFO - [2021-05-17 00:41:44,379] {local_task_job.py:103} INFO - Task exited with return code 1
